"""Initial migration

Revision ID: 7fd1ecdb54e8
Revises: 
Create Date: 2024-11-10 00:44:45.988501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fd1ecdb54e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('purchased_amount', sa.Float(), nullable=True),
    sa.Column('purchased_status', sa.String(), nullable=True),
    sa.Column('request_data', sa.Date(), nullable=True),
    sa.Column('company_code', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('stock_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performance_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('competitors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_company_code'), 'stocks', ['company_code'], unique=False)
    op.create_index(op.f('ix_stocks_id'), 'stocks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_id'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_company_code'), table_name='stocks')
    op.drop_table('stocks')
    # ### end Alembic commands ###
